# Generated by Django 3.2.3 on 2021-05-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Major', models.CharField(max_length=100)),
                ('Hobby', models.CharField(max_length=200)),
            ],
        ),
    ]
