# Generated by Django 3.2.3 on 2021-05-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20210513_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Class',
        ),
    ]
