# Generated by Django 3.2.3 on 2021-05-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_remove_member_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Class',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='Hobby',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='Major',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='Name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
