# Generated by Django 3.2.3 on 2021-05-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=200)),
                ('information', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
            ],
        ),
    ]
